#!/usr/bin/env bash
# changeset .md 파일 생성 후 커밋 반영 스크립트

if [ "$SKIP_HOOKS" = "true" ]; then
  exit 0
fi

export SKIP_HOOKS=true

node .githooks/scripts/changeset.js

if ls .changeset/*.md > /dev/null 2>&1; then
  git add .changeset/
  git commit --amend --no-edit
fi

exit 0
