import { PopoverPlacementPosition } from '@/components/Popover/Popover/types';

export const POPOVER_POSITION_DIVISION = '-';

export const POPOVER_POSITIONS = {
  BOTTOM: 'bottom',
  TOP: 'top',
  LEFT: 'left',
  RIGHT: 'right',
} as const;

export const POPOVER_PLACEMENTS = {
  BOTTOM_LEFT: `${POPOVER_POSITIONS.BOTTOM}${POPOVER_POSITION_DIVISION}${POPOVER_POSITIONS.LEFT}`,
  BOTTOM_RIGHT: `${POPOVER_POSITIONS.BOTTOM}${POPOVER_POSITION_DIVISION}${POPOVER_POSITIONS.RIGHT}`,
  TOP_LEFT: `${POPOVER_POSITIONS.TOP}${POPOVER_POSITION_DIVISION}${POPOVER_POSITIONS.LEFT}`,
  TOP_RIGHT: `${POPOVER_POSITIONS.TOP}${POPOVER_POSITION_DIVISION}${POPOVER_POSITIONS.RIGHT}`,
} as const;

export const POPOVER_PLACEMENT_POSITION_FLIPS: Record<
  PopoverPlacementPosition,
  PopoverPlacementPosition
> = {
  [POPOVER_POSITIONS.BOTTOM]: POPOVER_POSITIONS.TOP,
  [POPOVER_POSITIONS.TOP]: POPOVER_POSITIONS.BOTTOM,
  [POPOVER_POSITIONS.LEFT]: POPOVER_POSITIONS.RIGHT,
  [POPOVER_POSITIONS.RIGHT]: POPOVER_POSITIONS.LEFT,
};
