export const TYPOGRAPHY_ELEMENTS = {
  SPAN: 'span',
  P: 'p',
  H1: 'h1',
  H2: 'h2',
  H3: 'h3',
  H4: 'h4',
  H5: 'h5',
  H6: 'h6',
  B: 'b',
  EM: 'em',
  I: 'i',
  PRE: 'pre',
  STRONG: 'strong',
  ABBR: 'abbr',
  SUB: 'sub',
  Q: 'q',
  ADDRESS: 'address',
  CODE: 'code',
  DFN: 'dfn',
  MARK: 'mark',
  SMALL: 'small',
  SUP: 'sup',
  TIME: 'time',
  FIGCAPTION: 'figcaption',
  DT: 'dt',
  DD: 'dd',
} as const;
