import { TypographyVariants } from '@/variants/typography/types';

export const TYPOGRAPHY_VARIANTS = {
  DISPLAY_34_B: 'display-34-b',
  DISPLAY_34_M: 'display-34-m',
  DISPLAY_30_B: 'display-30-b',
  DISPLAY_30_M: 'display-30-m',
  HEADLINE_24_B: 'headline-24-b',
  HEADLINE_24_M: 'headline-24-m',
  HEADLINE_20_B: 'headline-20-b',
  HEADLINE_20_M: 'headline-20-m',
  BODY_18_B: 'body-18-b',
  BODY_18_M: 'body-18-m',
  BODY_18_R: 'body-18-r',
  BODY_16_B: 'body-16-b',
  BODY_16_M: 'body-16-m',
  BODY_16_R: 'body-16-r',
  BODY_14_B: 'body-14-b',
  BODY_14_M: 'body-14-m',
  BODY_14_R: 'body-14-r',
  BODY_12_B: 'body-12-b',
  BODY_12_M: 'body-12-m',
} as const;

export const TYPOGRAPHY_PREFIX = 'text-';

export const TYPOGRAPHY_STYLES_MAPPER: Record<TypographyVariants, string> = {
  [TYPOGRAPHY_VARIANTS.DISPLAY_34_B]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.DISPLAY_34_B}`,
  [TYPOGRAPHY_VARIANTS.DISPLAY_34_M]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.DISPLAY_34_M}`,
  [TYPOGRAPHY_VARIANTS.DISPLAY_30_B]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.DISPLAY_30_B}`,
  [TYPOGRAPHY_VARIANTS.DISPLAY_30_M]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.DISPLAY_30_M}`,
  [TYPOGRAPHY_VARIANTS.HEADLINE_24_B]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADLINE_24_B}`,
  [TYPOGRAPHY_VARIANTS.HEADLINE_24_M]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADLINE_24_M}`,
  [TYPOGRAPHY_VARIANTS.HEADLINE_20_B]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADLINE_20_B}`,
  [TYPOGRAPHY_VARIANTS.HEADLINE_20_M]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADLINE_20_M}`,
  [TYPOGRAPHY_VARIANTS.BODY_18_B]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_18_B}`,
  [TYPOGRAPHY_VARIANTS.BODY_18_M]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_18_M}`,
  [TYPOGRAPHY_VARIANTS.BODY_18_R]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_18_R}`,
  [TYPOGRAPHY_VARIANTS.BODY_16_B]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_16_B}`,
  [TYPOGRAPHY_VARIANTS.BODY_16_M]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_16_M}`,
  [TYPOGRAPHY_VARIANTS.BODY_16_R]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_16_R}`,
  [TYPOGRAPHY_VARIANTS.BODY_14_B]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_14_B}`,
  [TYPOGRAPHY_VARIANTS.BODY_14_M]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_14_M}`,
  [TYPOGRAPHY_VARIANTS.BODY_14_R]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_14_R}`,
  [TYPOGRAPHY_VARIANTS.BODY_12_B]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_12_B}`,
  [TYPOGRAPHY_VARIANTS.BODY_12_M]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_12_M}`,
};
