export * from '@/clipboard';
export * from '@/composeEventHandler';
export * from '@/date';
export * from '@/device';
export * from '@/excelDownload';
export * from '@/executeFunction';
export * from '@/extractDifferences';
export * from '@/extractExt';
export * from '@/getUUID';
export * from '@/hasUserAgent';
export * from '@/highlightText';
export * from '@/isServer';
export * from '@/mergeRefs';
export * from '@/parseExt';
export * from '@/removeExt';
export * from '@/storage';
export * from '@/toAbstractString';
export * from '@/toast';
export * from '@/toPaddedString';

export { ACCEPT_FILE_EXT, ACCEPT_FILES } from '@/shared';
export type { ExtFnProps } from '@/shared';
