export const RESPONSIBLE_STATUS = {
  MOBILE: 'MOBILE',
  TABLET: 'TABLET',
  DESKTOP: 'DESKTOP',
} as const;

export const BREAKPOINT_SIZE = {
  [RESPONSIBLE_STATUS.MOBILE]: 360,
  [RESPONSIBLE_STATUS.TABLET]: 820,
  [RESPONSIBLE_STATUS.DESKTOP]: 1180,
} as const;
