import { TypographyVariants } from '@/variants/typography/types';

export const TYPOGRAPHY_VARIANTS = {
  HEADING_1_BOLD: 'heading-1-bold',
  HEADING_1: 'heading-1',
  HEADING_2_BOLD: 'heading-2-bold',
  HEADING_2: 'heading-2',
  HEADING_3_BOLD: 'heading-3-bold',
  HEADING_3: 'heading-3',
  HEADING_4_BOLD: 'heading-4-bold',
  HEADING_4: 'heading-4',
  HEADING_5: 'heading-5',
  BODY_LG_SEMIBOLD: 'body-lg-semibold',
  BODY_LG: 'body-lg',
  BODY_BOLD: 'body-bold',
  BODY_SEMIBOLD: 'body-semibold',
  BODY: 'body',
  LABEL_BOLD: 'label-bold',
  LABEL_SEMIBOLD: 'label-semibold',
  LABEL: 'label',
  CAPTION: 'caption',
} as const;

export const TYPOGRAPHY_PREFIX = 'text-';

export const TYPOGRAPHY_STYLES_MAPPER: Record<TypographyVariants, string> = {
  [TYPOGRAPHY_VARIANTS.HEADING_1_BOLD]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADING_1_BOLD}`,
  [TYPOGRAPHY_VARIANTS.HEADING_1]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADING_1}`,
  [TYPOGRAPHY_VARIANTS.HEADING_2_BOLD]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADING_2_BOLD}`,
  [TYPOGRAPHY_VARIANTS.HEADING_2]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADING_2}`,
  [TYPOGRAPHY_VARIANTS.HEADING_3_BOLD]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADING_3_BOLD}`,
  [TYPOGRAPHY_VARIANTS.HEADING_3]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADING_3}`,
  [TYPOGRAPHY_VARIANTS.HEADING_4_BOLD]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADING_4_BOLD}`,
  [TYPOGRAPHY_VARIANTS.HEADING_4]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADING_4}`,
  [TYPOGRAPHY_VARIANTS.HEADING_5]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.HEADING_5}`,
  [TYPOGRAPHY_VARIANTS.BODY_LG_SEMIBOLD]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_LG_SEMIBOLD}`,
  [TYPOGRAPHY_VARIANTS.BODY_LG]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_LG}`,
  [TYPOGRAPHY_VARIANTS.BODY_BOLD]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_BOLD}`,
  [TYPOGRAPHY_VARIANTS.BODY_SEMIBOLD]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY_SEMIBOLD}`,
  [TYPOGRAPHY_VARIANTS.BODY]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.BODY}`,
  [TYPOGRAPHY_VARIANTS.LABEL_BOLD]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.LABEL_BOLD}`,
  [TYPOGRAPHY_VARIANTS.LABEL_SEMIBOLD]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.LABEL_SEMIBOLD}`,
  [TYPOGRAPHY_VARIANTS.LABEL]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.LABEL}`,
  [TYPOGRAPHY_VARIANTS.CAPTION]: `${TYPOGRAPHY_PREFIX}${TYPOGRAPHY_VARIANTS.CAPTION}`,
};
