import {
  CalendarDayVariants,
  CalendarWeekWeeks,
  CalendarWeeksValues,
} from '@/components/Calendar/types';
import {
  COLOR_STYLES_MAPPER,
  COLOR_VARIANTS,
  ColorVariants,
  TYPOGRAPHY_VARIANTS,
  TypographyVariants,
} from '@/variants';

export const CALENDAR_VARIANTS = {
  SINGLE: 'single',
  RANGE: 'range',
  UNBOUNDED: 'unbounded',
} as const;

export const CALENDAR_NAVIGATE_TYPE = {
  PREV: 'prev',
  NEXT: 'next',
} as const;

export const CALENDAR_NAVIGATE_META_DATA = {
  [CALENDAR_NAVIGATE_TYPE.PREV]: {
    LABEL: '이전 년도',
    ICON_KEY: 'caret-left',
  },
  [CALENDAR_NAVIGATE_TYPE.NEXT]: {
    LABEL: '다음 년도',
    ICON_KEY: 'caret-right',
  },
} as const;

export const CALENDAR_DAY_VARIANTS = {
  TODAY: 'today',
  STARTED: 'started',
  ENDED: 'ended',
  SELECTED_RANGE: 'selected_range',
  SELECTED_RANGE_SINGLE: 'selected_range_single',
  SELECTED_SINGLE: 'selected_single',
  SELECTED_DISABLED: 'selected_disabled',
  HOLIDAY_ENABLE: 'holiday_enable',
  HOLIDAY_DISABLED: 'holiday_disabled',
  SUNDAY_ENABLE: 'sunday_enable',
  SUNDAY_DISABLED: 'sunday_disabled',
  SATURDAY_ENABLE: 'saturday_enable',
  SATURDAY_DISABLED: 'saturday_disabled',
  DEFAULT_DISABLED: 'default_disabled',
  DEFAULT_ENABLE: 'default_enable',
} as const;

export const CALENDAR_DAY_STYLES: Record<
  CalendarDayVariants,
  {
    COLOR: ColorVariants;
    BACKGROUND: string;
    VARIANT: TypographyVariants;
    ROUNDED: string;
  }
> = {
  [CALENDAR_DAY_VARIANTS.DEFAULT_ENABLE]: {
    COLOR: COLOR_VARIANTS.BLACK,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.DEFAULT_DISABLED]: {
    COLOR: COLOR_VARIANTS.GRAY_03,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.STARTED]: {
    COLOR: COLOR_VARIANTS.WHITE,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_05],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_B,
    ROUNDED: 'rounded-l-in-12',
  },
  [CALENDAR_DAY_VARIANTS.ENDED]: {
    COLOR: COLOR_VARIANTS.WHITE,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_05],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_B,
    ROUNDED: 'rounded-r-in-12',
  },
  [CALENDAR_DAY_VARIANTS.SELECTED_RANGE]: {
    COLOR: COLOR_VARIANTS.PRIMARY_06,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_02],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SELECTED_RANGE_SINGLE]: {
    COLOR: COLOR_VARIANTS.WHITE,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_05],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_B,
    ROUNDED: 'rounded-in-12',
  },
  [CALENDAR_DAY_VARIANTS.SELECTED_SINGLE]: {
    COLOR: COLOR_VARIANTS.WHITE,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_05],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_B,
    ROUNDED: 'rounded-in-12',
  },
  [CALENDAR_DAY_VARIANTS.SELECTED_DISABLED]: {
    COLOR: COLOR_VARIANTS.PRIMARY_06,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_02],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.TODAY]: {
    COLOR: COLOR_VARIANTS.PRIMARY_06,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.HOLIDAY_ENABLE]: {
    COLOR: COLOR_VARIANTS.RED_07,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.HOLIDAY_DISABLED]: {
    COLOR: COLOR_VARIANTS.RED_03,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SATURDAY_ENABLE]: {
    COLOR: COLOR_VARIANTS.BLACK,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SATURDAY_DISABLED]: {
    COLOR: COLOR_VARIANTS.GRAY_03,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SUNDAY_ENABLE]: {
    COLOR: COLOR_VARIANTS.RED_07,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SUNDAY_DISABLED]: {
    COLOR: COLOR_VARIANTS.RED_03,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
};

export const CALENDAR_DAY_SELECTED_VARIANTS: CalendarDayVariants[] = [
  CALENDAR_DAY_VARIANTS.STARTED,
  CALENDAR_DAY_VARIANTS.ENDED,
  CALENDAR_DAY_VARIANTS.SELECTED_RANGE,
  CALENDAR_DAY_VARIANTS.SELECTED_SINGLE,
  CALENDAR_DAY_VARIANTS.SELECTED_DISABLED,
  CALENDAR_DAY_VARIANTS.SELECTED_RANGE_SINGLE,
];

export const CALENDAR_DAY_DISABLED_VARIANTS: CalendarDayVariants[] = [
  CALENDAR_DAY_VARIANTS.DEFAULT_DISABLED,
  CALENDAR_DAY_VARIANTS.HOLIDAY_DISABLED,
  CALENDAR_DAY_VARIANTS.SUNDAY_DISABLED,
  CALENDAR_DAY_VARIANTS.SATURDAY_DISABLED,
  CALENDAR_DAY_VARIANTS.SELECTED_DISABLED,
];

export const CALENDAR_WEEKS = {
  SUNDAY: 'sunday',
  MONDAY: 'monday',
  TUESDAY: 'tuesday',
  WEDNESDAY: 'wednesday',
  THURSDAY: 'thursday',
  FRIDAY: 'friday',
  SATURDAY: 'saturday',
} as const;

export const CALENDAR_WEEKS_META_DATA: Record<
  CalendarWeekWeeks,
  {
    VALUE: CalendarWeeksValues;
    LABEL: { SHORT: string; LONG: string };
  }
> = {
  [CALENDAR_WEEKS.SUNDAY]: {
    VALUE: 0,
    LABEL: {
      SHORT: '일',
      LONG: '일요일',
    },
  },
  [CALENDAR_WEEKS.MONDAY]: {
    VALUE: 1,
    LABEL: {
      SHORT: '월',
      LONG: '월요일',
    },
  },
  [CALENDAR_WEEKS.TUESDAY]: {
    VALUE: 2,
    LABEL: {
      SHORT: '화',
      LONG: '화요일',
    },
  },
  [CALENDAR_WEEKS.WEDNESDAY]: {
    VALUE: 3,
    LABEL: {
      SHORT: '수',
      LONG: '수요일',
    },
  },
  [CALENDAR_WEEKS.THURSDAY]: {
    VALUE: 4,
    LABEL: {
      SHORT: '목',
      LONG: '목요일',
    },
  },
  [CALENDAR_WEEKS.FRIDAY]: {
    VALUE: 5,
    LABEL: {
      SHORT: '금',
      LONG: '금요일',
    },
  },
  [CALENDAR_WEEKS.SATURDAY]: {
    VALUE: 6,
    LABEL: {
      SHORT: '토',
      LONG: '토요일',
    },
  },
};

export const WEEKS = Object.values(CALENDAR_WEEKS);
export const CALENDAR_MONTHLY_COUNT = 12;
export const CALENDAR_DAYS_ROW_COUNT = 5;
export const CALENDAR_WEEKS_COUNT = WEEKS.length;
export const CALENDAR_DAYS_COUNT =
  CALENDAR_WEEKS_COUNT * CALENDAR_DAYS_ROW_COUNT;
export const CALENDAR_MONTHLY_ARRAY = Array.from(
  { length: CALENDAR_MONTHLY_COUNT },
  (_, i) => i,
);
export const CALENDAR_DAYS_ARRAY = Array.from(
  { length: CALENDAR_DAYS_ROW_COUNT },
  (_, i) => i,
);
export const CALENDAR_WEEKS_ARRAY = Array.from(
  { length: CALENDAR_WEEKS_COUNT },
  (_, i) => i,
);

export const CALENDAR_DEFAULT_LABELS = {
  TODAY: '오늘',
  HOLIDAY: '공휴일',
} as const;
