import {
  CalendarDayVariants,
  CalendarWeekWeeks,
  CalendarWeeksValues,
} from '@/components/Calendar/types';
import {
  COLOR_STYLES_MAPPER,
  COLOR_VARIANTS,
  ColorVariants,
  TYPOGRAPHY_VARIANTS,
  TypographyVariants,
} from '@/variants';

export const CALENDAR_VARIANTS = {
  SINGLE: 'SINGLE',
  RANGE: 'RANGE',
  UNBOUNDED: 'UNBOUNDED',
} as const;

export const CALENDAR_NAVIGATE_TYPE = {
  PREV: 'PREV',
  NEXT: 'NEXT',
} as const;

export const CALENDAR_NAVIGATE_META_DATA = {
  [CALENDAR_NAVIGATE_TYPE.PREV]: {
    LABEL: '이전 년도',
    ICON_KEY: 'caret-left',
  },
  [CALENDAR_NAVIGATE_TYPE.NEXT]: {
    LABEL: '다음 년도',
    ICON_KEY: 'caret-right',
  },
} as const;

export const CALENDAR_DAY_VARIANTS = {
  TODAY: 'TODAY',
  STARTED: 'STARTED',
  ENDED: 'ENDED',
  SELECTED_RANGE: 'SELECTED_RANGE',
  SELECTED_SINGLE: 'SELECTED_SINGLE',
  SELECTED_DISABLED: 'SELECTED_DISABLED',
  HOLIDAY_ENABLE: 'HOLIDAY_ENABLE',
  HOLIDAY_DISABLE: 'HOLIDAY_DISABLE',
  SUNDAY_ENABLE: 'SUNDAY_ENABLE',
  SUNDAY_DISABLE: 'SUNDAY_DISABLE',
  SATURDAY_ENABLE: 'SATURDAY_ENABLE',
  SATURDAY_DISABLE: 'SATURDAY_DISABLE',
  DEFAULT_DISABLE: 'DEFAULT_DISABLE',
  DEFAULT_ENABLE: 'DEFAULT_ENABLE',
} as const;

export const CALENDAR_DAY_STYLES: Record<
  CalendarDayVariants,
  {
    COLOR: ColorVariants;
    BACKGROUND: string;
    VARIANT: TypographyVariants;
    ROUNDED: string;
  }
> = {
  [CALENDAR_DAY_VARIANTS.DEFAULT_ENABLE]: {
    COLOR: COLOR_VARIANTS.BLACK,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.DEFAULT_DISABLE]: {
    COLOR: COLOR_VARIANTS.GRAY_03,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.STARTED]: {
    COLOR: COLOR_VARIANTS.WHITE,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_05],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_B,
    ROUNDED: 'rounded-l-in-12',
  },
  [CALENDAR_DAY_VARIANTS.ENDED]: {
    COLOR: COLOR_VARIANTS.WHITE,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_05],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_B,
    ROUNDED: 'rounded-r-in-12',
  },
  [CALENDAR_DAY_VARIANTS.SELECTED_RANGE]: {
    COLOR: COLOR_VARIANTS.PRIMARY_06,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_02],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SELECTED_SINGLE]: {
    COLOR: COLOR_VARIANTS.WHITE,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_05],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_B,
    ROUNDED: 'rounded-in-12',
  },
  [CALENDAR_DAY_VARIANTS.SELECTED_DISABLED]: {
    COLOR: COLOR_VARIANTS.PRIMARY_06,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.PRIMARY_02],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.TODAY]: {
    COLOR: COLOR_VARIANTS.PRIMARY_06,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.HOLIDAY_ENABLE]: {
    COLOR: COLOR_VARIANTS.RED_07,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.HOLIDAY_DISABLE]: {
    COLOR: COLOR_VARIANTS.RED_03,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SATURDAY_ENABLE]: {
    COLOR: COLOR_VARIANTS.BLACK,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SATURDAY_DISABLE]: {
    COLOR: COLOR_VARIANTS.GRAY_03,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SUNDAY_ENABLE]: {
    COLOR: COLOR_VARIANTS.RED_07,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
  [CALENDAR_DAY_VARIANTS.SUNDAY_DISABLE]: {
    COLOR: COLOR_VARIANTS.RED_03,
    BACKGROUND: COLOR_STYLES_MAPPER.BACKGROUND[COLOR_VARIANTS.WHITE],
    VARIANT: TYPOGRAPHY_VARIANTS.BODY_14_R,
    ROUNDED: 'rounded-none',
  },
};

export const CALENDAR_DAY_SELECTED_VARIANTS: CalendarDayVariants[] = [
  CALENDAR_DAY_VARIANTS.STARTED,
  CALENDAR_DAY_VARIANTS.ENDED,
  CALENDAR_DAY_VARIANTS.SELECTED_RANGE,
  CALENDAR_DAY_VARIANTS.SELECTED_SINGLE,
  CALENDAR_DAY_VARIANTS.SELECTED_DISABLED,
];

export const CALENDAR_DAY_DISABLED_VARIANTS: CalendarDayVariants[] = [
  CALENDAR_DAY_VARIANTS.DEFAULT_DISABLE,
  CALENDAR_DAY_VARIANTS.HOLIDAY_DISABLE,
  CALENDAR_DAY_VARIANTS.SUNDAY_DISABLE,
  CALENDAR_DAY_VARIANTS.SATURDAY_DISABLE,
  CALENDAR_DAY_VARIANTS.SELECTED_DISABLED,
];

export const CALENDAR_WEEKS = {
  SUNDAY: 'SUNDAY',
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
} as const;

export const CALENDAR_WEEKS_META_DATA: Record<
  CalendarWeekWeeks,
  {
    VALUE: CalendarWeeksValues;
    LABEL: { SHORT: string; LONG: string };
  }
> = {
  [CALENDAR_WEEKS.SUNDAY]: {
    VALUE: 0,
    LABEL: {
      SHORT: '일',
      LONG: '일요일',
    },
  },
  [CALENDAR_WEEKS.MONDAY]: {
    VALUE: 1,
    LABEL: {
      SHORT: '월',
      LONG: '월요일',
    },
  },
  [CALENDAR_WEEKS.TUESDAY]: {
    VALUE: 2,
    LABEL: {
      SHORT: '화',
      LONG: '화요일',
    },
  },
  [CALENDAR_WEEKS.WEDNESDAY]: {
    VALUE: 3,
    LABEL: {
      SHORT: '수',
      LONG: '수요일',
    },
  },
  [CALENDAR_WEEKS.THURSDAY]: {
    VALUE: 4,
    LABEL: {
      SHORT: '목',
      LONG: '목요일',
    },
  },
  [CALENDAR_WEEKS.FRIDAY]: {
    VALUE: 5,
    LABEL: {
      SHORT: '금',
      LONG: '금요일',
    },
  },
  [CALENDAR_WEEKS.SATURDAY]: {
    VALUE: 6,
    LABEL: {
      SHORT: '토',
      LONG: '토요일',
    },
  },
};

export const WEEKS = Object.values(CALENDAR_WEEKS);
export const CALENDAR_MONTHLY_COUNT = 12;
export const CALENDAR_DAYS_ROW_COUNT = 5;
export const CALENDAR_WEEKS_COUNT = WEEKS.length;
export const CALENDAR_DAYS_COUNT =
  CALENDAR_WEEKS_COUNT * CALENDAR_DAYS_ROW_COUNT;
export const CALENDAR_MONTHLY_ARRAY = Array.from(
  { length: CALENDAR_MONTHLY_COUNT },
  (_, i) => i,
);
export const CALENDAR_DAYS_ARRAY = Array.from(
  { length: CALENDAR_DAYS_ROW_COUNT },
  (_, i) => i,
);
export const CALENDAR_WEEKS_ARRAY = Array.from(
  { length: CALENDAR_WEEKS_COUNT },
  (_, i) => i,
);
