name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm prebuild
          build_command: pnpm in build && pnpm ut build && pnpm hooks build  && pnpm sb build
          path: apps/storybook/storybook-static
          checkout: true
