name: Publish Changed Packages

on:
  push:
    branches:
      - DOTOLI-142

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
      - uses: actions/checkout@v4

      - name: Setup pnpm
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build only changed packages
        run: pnpm turbo run build --filter=...[HEAD^1]

      - name: Create changelogs & bump versions
        run: pnpm changeset version

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm changeset publish
